Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  config.vm.hostname = "idelemenS"
  config.vm.network "private_network", ip: "192.168.56.110"
  config.vm.synced_folder ".", "/home/vagrant/apps"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "idelemenS"
    vb.memory = "2048"
    vb.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt update && apt install -y curl
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--bind-address=192.168.56.110 --node-ip=192.168.56.110" sh -s -
  SHELL
end
