Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  config.vm.define "ercdenizS" do |server|
    server.vm.hostname = "ercdenizS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.name = "ercdenizS"
      vb.memory = 2048
      vb.cpus = 2
    end
    server.vm.provision "shell", path: "scripts/install_k3s_server.sh"
  end
end
