Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  config.vm.define "ercdenizS" do |server|
    server.vm.hostname = "ercdenizS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.name = "ercdenizS"
      vb.memory = 1024
      vb.cpus = 1
    end
    server.vm.provision "shell", path: "scripts/install_k3s_server.sh"
  end

  config.vm.define "ercdenizSW" do |worker|
    worker.vm.hostname = "ercdenizSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |vb|
      vb.name = "ercdenizSW"
      vb.memory = 1024
      vb.cpus = 1
    end
    worker.vm.provision "shell", path: "scripts/install_k3s_agent.sh"
  end
end
